# Generated by Django 5.2.7 on 2025-10-05 22:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='hora_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
