# Generated by Django 5.2.7 on 2025-10-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0002_alter_visita_hora_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
